### ISSUE TITLE
`--skip-verify` flag does not work on `microk8s join`

### ISSUE THREAD

**Issue by AlecDusheck** [canonical/microk8s#2420]
When running the `microk8s join` command, it is possible to bypass certificate validation using the `--skip-verify` command. However, since PR https://github.com/ubuntu/microk8s/pull/1263, this does not appear to work as intended.

**If a sha hash is present in the server connection**, ex: `microk8s join 192.168.50.4:25000/70cd002331e153d402d815fd21304237`, **the `--skip-verify` argument is ignored!**

It appears that the `verify` variable is overwritten in the if block on line 944 (see https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/join.py#L944). It appears that this check for the sha hash ignores the current state of `verify`.

I'm not sure if this is intended behavior or not, but it's definitely misleading.

Inspection:
[inspection-report-20210712_014812.tar.gz](https://github.com/ubuntu/microk8s/files/6798127/inspection-report-20210712_014812.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @AlecDusheck 

A connection string such as `10.246.154.128:25000/4d54b690242a0e0acb4cc13ef3fa16cc/4c21df798f3a` is made of 3 parts:

 - the ip and port of the node to contact (`10.246.154.128:25000`)
 - the connection token (`4d54b690242a0e0acb4cc13ef3fa16cc`)
 - and a verification fingerprint (`4c21df798f3a`)

If the verification fingerprint is missing the node is not verified. This is intentional so as to maintain backwards compatibility (join to clusters where we do not have the fingerprint). If the verification fingerprint is present in the connection string but you do not want to get the node verified you can use the `--skip-verify` flag.

The connection string you mention above does not have the verification fingerprint so the `--skip-verify` is ignored.

**Comment by stefan55574** [comment]
I have same problem. Did you solve it ?

**Comment by neoaggelos** [comment]
Hi @stefan55574,

This has been fixed in latest master, and the fix is in the process of being backported to all supported versions ([1.21](https://github.com/canonical/microk8s/pull/3074), [1.22](#3073), [1.23](#3072)).

Fixes will be released `edge` after being merged, and are then promoted to `stable` after a week.

**Comment by smandalika** [comment]
I'm still getting this problem. How do I get it resolved? Please let me know
-Satty

**Comment by neoaggelos** [comment]
Hi @smandalika,

You can try the following:

```bash
# on the existing cluster node. restarting the service might not be needed
sudo snap restart microk8s.daemon-cluster-agent
microk8s add-node
```

This will give you a new join URL. You should then be able to use that to join your second node to the cluster.

**Comment by smandalika** [comment]
hmm I'm running it on a Mac and snap isn't supported on Mac. Any other way I can accomplish this?

**Comment by neoaggelos** [comment]
@smandalika You should run this command inside the Multipass VM where microk8s is running:

```bash
multipass shell microk8s-vm

# inside the vm
sudo snap restart microk8s
```
