### ISSUE TITLE
MicroK8s v1.2.5.0 - kubernetes-dashboard 404's cron Jobs

### ISSUE THREAD

**Issue by Barfooss** [canonical/microk8s#3451]
#### Summary
The packaged version of the kubernetes-dashboard in MicroK8s v1.25.0 is incompatible with the kubernetes api-version for listing Cron Jobs, resulting in a 404 response if navigating to "Cron Jobs" in the Dashboard.

#### What Should Happen Instead?
A List of the configured Cron Jobs in the namespace should be displayed.
See also bug report: https://github.com/kubernetes/dashboard/issues/7289
And fixed in merge https://github.com/kubernetes/dashboard/pull/7301

#### Reproduction Steps
Rollout microk8s v1.25.0, enable "dashboard", login to dashboard, click "Cron Jobs" in the left hand menu.

#### Introspection Report
[inspection-report-20220917_130201.tar.gz](https://github.com/canonical/microk8s/files/9591508/inspection-report-20220917_130201.tar.gz)

#### Can you suggest a fix?
Change version of packaged dashboard to 2.7.0

#### Are you interested in contributing with a fix?
no

<3

**Comment by trailblazn** [comment]
Thank you, I'm struggling with this issue too!

microk8s 1.25.0 and dashboard 2.6.0

Tried dashboard 2.7.0, same issue.

**Comment by trailblazn** [comment]
Finally, seems my issue was version mismatch too.

Resolved with dashboard 2.7.0 and
![image](https://user-images.githubusercontent.com/8889088/190889000-2a0912bd-b3b5-4211-ba6d-0d70e5ffb4d5.png)

**Comment by neoaggelos** [comment]
Kubernetes Dashboard 2.6.0 and older is using `batch/v1beta1` to access cronjobs, which is now removed in 1.25.

Dashboard 2.7.0 solves this issue, but there is still a minor bug when viewing the details a cronjob, which could be fixed by https://github.com/kubernetes/dashboard/pull/7465

Once the bugfixes are released, we will make sure to update the image of the dashboard addon as needed.

In the meantime, you can fix the list of the cronjobs by manually updating the dashboard image:

```
microk8s kubectl set image -n kube-system deploy/kubernetes-dashboard kubernetes-dashboard=kubernetesui/dashboard:v2.7.0
```

**Comment by krichter722** [comment]
@neoaggelos FYI, I'm still experiencing the issue with `kubernetesui/dashboard:v2.7.0` with microk8s v1.25.3 (snap 4094). The cronjob with `apiVersion: batch/v1` is displayed in the list of cronjobs, but opening the details causes `Not Found (404) the server could not find the requested resource`.

The issue was originally filed for the list of cronjobs which I can open, but I guess there's still a similar problem with the details now. Would you like me to file a separate issue for this. Do you have any idea if there's an upstream issue for the details already - I couldn't find one?

**Comment by neoaggelos** [comment]
Hi @krichter722 

Dashboard version 2.7.0 fixes the issue with the cronjob list, but then, as you mentioned, opening an individual cronjob still fails with 404.

The linked PR https://github.com/kubernetes/dashboard/pull/7465 fixes this and has been merged to master, but there still has not been a release that includes it yet. Supposedly, this will be release 2.7.1, and judging from the release cycle of the kubernetes dashboard project, it should come soon enough.

We are keeping an eye on it and will make sure to update the addon version accordingly.

**Comment by neoaggelos** [comment]
FYI; there is still no new k/dashboard release

**Comment by fontexD** [comment]
any update on this ? could be nice to be able to see the details of the cronjobs :)

**Comment by neoaggelos** [comment]
Hi @fontexD

Unfortunately, upstream has yet to release the fix https://github.com/kubernetes/dashboard/pull/7465#issuecomment-1429981451

**Comment by fontexD** [comment]
I looked in the code for the cronjon and it seems fixed but last update was 6 month ago, was the fix already applied there? I could just compile current branch then and use it locally

**Comment by bhutkovskyysos** [comment]
> I looked in the code for the cronjon and it seems fixed but last update was 6 month ago, was the fix already applied there? I could just compile current branch then and use it locally

that is what I'd like to do as well. Are there any instructions on how to compile it and build the docker image for it?

**Comment by beffe123** [comment]
For everyone interested, I've created a fixed version based on kuberentes dashboard version v2.7.0. I've published it on docker hub: beffe/kubernetes-dashboard:v2.7.0-fix-cj-2

You can find the code changes here:
https://github.com/kubernetes/dashboard/compare/master...beffe123:kubernetes-dashboard:v2.7.0-fixes
