### ISSUE TITLE
Frequent 'database is locked error' 500 on lease update

### ISSUE THREAD

**Issue by cs-dsmyth** [canonical/microk8s#5153]
#### Summary
Seeing as below whereby a small number of lease updates in k8s results in a large number of duplicate update queries in k8s-dqlite.

This issue is observed in v1.32 and v1.33 microk8s, not seen in a previous version used v1.29 so suspect some change has introduced the behaviour.

Example below 1 lease update for kube-controller-manager

kubectl get leases --all-namespaces --watch | grep kube-controller-manager

```
2025-07-21 15:04:50.475  pods    kube-system       kube-controller-manager                                     dailybuild4-host1_53ce2bb9-14e4-46af-83c0-bde7007e05c3                      9h
``` 

Debug logging turned up in '/var/snap/microk8s/current/args/k8s-dqlite' this results in 327 of these update queries in one second.
For some reason that same update is getting fired many times internally.

labuser@dailybuild4-host1:~$ sudo journalctl -u snap.microk8s.daemon-k8s-dqlite | grep '15:04:50' | grep kube-controller-manager | grep INSERT | wc -l
327

``` 
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-k8s-dqlite[971627]: time="2025-07-21T15:04:50+01:00" level=debug msg="EXEC (try: 499) [/registry/leases/kube-system/kube-controller-manager 0 [107 56 115 0 10 31 10 22 99 111 111 114 100 105 110 97 116 105 111 110 46 107 56 115 46 105 111 47 118 49 18 5 76 101 97 115 101 18 253 2 10 160 2 10 23 107 117 98 101 45 99 111 110 116 114 111 108 108 101 114 45 109 97 110 97 103 101 114 18 0 26 11 107 117 98 101 45 115 121 115 116 101 109 34 0 42 36 100 99 52 101 100 101 101 98 45 51 97 99 51 45 52 98 55 101 45 98 102 49 54 45 101 102 55 51 97 97 51 98 55 52 51 50 50 0 56 0 66 8 8 245 138 247 195 6 16 0 138 1 190 1 10 8 107 117 98 101 108 105 116 101 18 6 85 112 100 97 116 101 26 22 99 111 111 114 100 105 110 97 116 105 111 110 46 107 56 115 46 105 111 47 118 49 34 8 8 129 146 249 195 6 16 0 50 8 70 105 101 108 100 115 86 49 58 124 10 122 123 34 102 58 115 112 101 99 34 58 123 34 102 58 97 99 113 117 105 114 101 84 105 109 101 34 58 123 125 44 34 102 58 104 111 108 100 101 114 73 100 101 110 116 105 116 121 34 58 123 125 44 34 102 58 108 101 97 115 101 68 117 114 97 116 105 111 110 83 101 99 111 110 100 115 34 58 123 125 44 34 102 58 108 101 97 115 101 84 114 97 110 115 105 116 105 111 110 115 34 58 123 125 44 34 102 58 114 101 110 101 119 84 105 109 101 34 58 123 125 125 125 66 0 18 88 10 54 100 97 105 108 121 98 117 105 108 100 52 45 104 111 115 116 49 95 53 51 99 101 50 98 98 57 45 49 52 101 52 45 52 54 97 102 45 56 51 99 48 45 98 100 101 55 48 48 55 101 48 53 99 51 16 60 26 12 8 188 198 248 195 6 16 248 236 250 173 3 34 12 8 129 146 249 195 6 16 128 173 136 153 3 40 6 26 0 34 0] /registry/leases/kube-system/kube-controller-manager 202186] :  INSERT INTO kine(name, created, deleted, create_revision, prev_revision, lease, value, old_value) SELECT ? AS name, 0 AS created, 0 AS deleted, CASE WHEN kine.created THEN id ELSE create_revision END AS create_revision, id AS prev_revision, ? AS lease, ? AS value, value AS old_value FROM kine WHERE id = (SELECT MAX(id) FROM kine WHERE name = ?) AND deleted = 0 AND id = ?"
``` 

The result is the following error in syslog, and the action fails.

``` 
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-kubelite[283598]: E0721 15:04:50.129980  283598 status.go:71] "Unhandled Error" err="apiserver received an error that is not an metav1.Status: &status.Error{s:(*status.Status)(0xc01fcd4378)}: rpc error: code = Unknown desc = exec (try: 500): database is locked"
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-kubelite[283598]: E0721 15:04:50.132155  283598 leaderelection.go:429] Failed to update lock optimistically: rpc error: code = Unknown desc = exec (try: 500): database is locked, falling back to slow path
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-k8s-dqlite[971627]: time="2025-07-21T15:04:50+01:00" level=error msg="failed to update key" error="exec (try: 500): database is locked"
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-k8s-dqlite[971627]: time="2025-07-21T15:04:50+01:00" level=debug msg="UPDATE /registry/leases/kube-system/kube-controller-manager, value=425, rev=202186, lease=0 => rev=0, updated=false, err=exec (try: 500): database is locked"
Jul 21 15:04:50 dailybuild4-host1 microk8s.daemon-k8s-dqlite[971627]: time="2025-07-21T15:04:50+01:00" level=error msg="error in txn: exec (try: 500): database is locked"
``` 

Seen on a single node microk8s and also 3 node cluster.
Introducing disk i/o provokes the issue further, assuming due to queries taking longer to run and therefore more likely to hit a lock condition.
Not particular to this one lease update event, happens for multiple different pods in the deployment.
Function being called in k8s-dqlite looks to be 'updateSQL' in pkg/backend/sqlite/driver.go.
Is there some situation in microk8s that this gets retried in quick succession or there is a very short timeout value for retry?

Happy to provide further logs if needed.

#### What Should Happen Instead?
No database is locked errors. This causes other k8s actions to fail.

#### Reproduction Steps
I can reproduce by introducing some disk load on the microk8s server eg by running

while true; do dd if=/dev/zero of=test1.img bs=40G count=1 oflag=dsync; done

**Comment by cs-dsmyth** [comment]
Attaching log file for example in report 
[snap.microk8s.daemon-k8s-dqlite.log.tar.gz](https://github.com/user-attachments/files/21415369/snap.microk8s.daemon-k8s-dqlite.log.tar.gz)

Also attaching another instance where the lease renewals are counted alongside the number of INSERT actions towards DQLite as seen in microk8s.daemon-k8s-dqlite logs with debug enabled   ( 229 lease updates result in 14,164 INSERTs)
[Example_insert_counts_vs_lease_updates.txt](https://github.com/user-attachments/files/21415381/Example_insert_counts_vs_lease_updates.txt)

**Comment by louiseschmidtgen** [comment]
Hi @cs-dsmyth,

thank you for filing your issue and attaching the logs. 

You are currently hitting a limitation of what your disk can handle. When introducing additional load on the disk of your microk8s cluster k8s-dqlite fails to make progress. Transactions, such as the lease update fail and are retried in quick succession (up to 500 times). 

We've been working on addressing this issue. Retries are being moved to the database side (Dqlite) and we are reducing the number of transactions per second from Kubernetes (by using batching) which reduces the pressure on the disk. 

In the meantime, while we are working on addressing this issue, you can use microk8s with an [external etcd](https://microk8s.io/docs/external-etcd) or try a candidate build (1.33-classic/candidate) of the [k8s-snap](https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/tutorial/getting-started/) with managed etcd.

Many thanks again for your feedback!

**Comment by cs-dsmyth** [comment]
Thanks for the info on this issue @louiseschmidtgen it's much appreciated.
Good to know I'm not the only one seeing it :) 

Is there another issue #ID that I can follow for the progress on addressing this as you mention it is a known problem.

Thanks,
David

**Comment by nelsinchi** [comment]
Hi, I have been facing the same issue in all the environments from Proxmox where I have been testing MicroK8s. Clearly, the error is pointing to the workload consumed on the disk caused by the `dqlite` issue/bug. Also, I found that this could also be related to the type of storage used, where the Kubernetes servers are hosted. I tested the same on Ceph storage with around 12 OSDs per Proxmox node for the storage synchronization, and the error blows up too frequently in the `/var/log/syslog`. But if I use LINSTOR storage as a Ceph replacement, the error occasionally appears in the log file. It is a very big difference.

Could you please explain what the prerequisites would be to install a functional cluster using K8s instead of MicroK8s, in terms of the number of master nodes, CPU, RAM, and so on?

Is the K8s alternative already including `etcd` instead of `dqlite`, or what are the benefits to installing MicroK8s with an `etcd` cluster externally?

Any direction to this would be much appreciated.

Thanks a lot in advance!

**Comment by louiseschmidtgen** [comment]
Hi @cs-dsmyth,

The issues have surfaced mostly internally, therefore I don't have another issue ID for you. You may keep this issue open until we've addressed it.

On a happy note, we now have a release from the Dqlite team and are working on bringing these changes into the next Microk8s release.

Best regards,
Louise

**Comment by louiseschmidtgen** [comment]
Hi @nelsinchi,

the issue boils down to the fact that you are not getting sufficient disk performance on your ceph with Dqlite set-up. The factors that apply here are too high disk latency and/or in a multi-node scenario you could see the same symptoms due to a slow network. Both don't allow Dqlite and therefore k8s to make progress at the necessary rate. We will be releasing fixes that will reduce the occurrence of this error significantly (unless your issue is due to a slow network).

You have a few options: wait on the fixes released with a newer Dqlite, use a disk with lower latency or consider the etcd alternative. The [k8s-snap](https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/howto/install/snap/) alternative (in candidate) has etcd backed into the snap whereas Microk8s only supports the [external etcd set-up](https://microk8s.io/docs/external-etcd) - meaning that it is managed by you. For resource requirements with etcd please consult their [upstream docs](https://etcd.io/docs/v3.3/op-guide/hardware/). The high availability requirements are the same across Dqlite and etcd as both build on the raft consensus algorithm. We recommend using three control plane nodes allowing for the fault tolerance of one node. 

I hope this helps you in making a better choice to fit your needs.

Best regards,
Louise

**Comment by nelsinchi** [comment]
Thank you very much, everyone, for your hard work in addressing this issue. We hope to have a permanent fix in the next MicroK8s release version :wink:.

**Comment by kcarson77** [comment]
thanks - seeing this also vmware VMs on fairly well spec'd hosts across multiple environments. These were fine on 1.29.
Will there be a patch to 1.32, which is our current deployment? Is there an ETA for the next release? Thanks again.

**Comment by louiseschmidtgen** [comment]
Hi @kcarson77, 

Currently, there is no plan to patch 1.32 as we generally don't back-port new features. The next release will depend on a new release of Dqlite and multiple larger changes on the layer between k8s and Dqlite. 

While this is probably not the answer you were hoping for, you should consider [upgrading your cluster](https://microk8s.io/docs/upgrading) to take advantage of the new performance improvements.

Best regards,
Louise

**Comment by kcarson77** [comment]
OK, thanks.
Do you mean next release of 1.33, or mean next release as in 1.34 at end of August?

**Comment by louiseschmidtgen** [comment]
Hi @kcarson77,

the improvements will be part of the 1.34 MiroK8s release.

**Comment by nelsinchi** [comment]
Hi @louiseschmidtgen, 

Please, do you have an estimated time when we could upgrade to the 1.34 version and test the issue?

Thanks a lot in advance!

**Comment by HomayoonAlimohammadi** [comment]
Hi @nelsinchi,

Microk8s 1.34 will be released shortly after upstream Kubernetes 1.34 is released.

**Comment by sibelius** [comment]
https://kubernetes.io/blog/2025/08/27/kubernetes-v1-34-release/

**Comment by MonkzCode** [comment]
Hello! 
Please, can someone give an answer, does this problem fixed in MK8s 1.34?
Thanks in advance!

**Comment by cs-dsmyth** [comment]
@MonkzCode Yes 1.34 looks much better. I still see the err500 database is locked on odd occasion - but instances are in the single digits at times of load vs thousands of these errors over a few seconds with previous releases.

**Comment by taurus-forever** [comment]
It looks like we have faced the same error on Charmed PostgreSQL testing tonight:
https://github.com/canonical/postgresql-k8s-operator/actions/runs/28987352388/job/86020084007#step:11:215
```
unit-postgresql-k8s-0: 01:35:35 ERROR juju.worker.uniter.operation hook "leader-elected" (via hook dispatching script: dispatch) failed: saving content for secret "bb4utvlbdhmdtsfnvka0": rpc error: code = Unknown desc = create transaction failed for key /registry/secrets/testing/bb4utvlbdhmdtsfnvka0-1: exec (try: 500): database is locked
```

Env:
```
juju        3.6.25      35378  3.6/stable          canonical**  -
kubectl     1.35.6      3816   latest/stable       canonical**  classic
microk8s    v1.36.2     9090   1.36-strict/stable  canonical**  -
```

**Comment by vikasvk1** [comment]
Still occurring on v1.34 under sustained production load.

**Setup**:  4-node HA cluster, 70+  ArgoCD applications continuously reconciling against the cluster.

**Symptom**:  exec (try: 500): database is locked recurs on roughly a weekly cycle. It builds up over ~35–38 days of node uptime until the cluster degrades — ArgoCD UI goes stale, new pods fail to start or can't reach cluster services, and Redis HA drops below quorum.

**Mitigation**:  a rolling reboot of all nodes (one at a time) reliably clears it and resets the cycle — but it's only temporary; the problem returns within roughly a week or two. Rebooting is currently the only thing that recovers the cluster.
Lock counts across all 4 nodes before a recent reboot (journalctl -u snap.microk8s.daemon-kubelite | grep -c "database is locked", 2-hour window): 260 / 24 / 113 / 315 — all nodes affected at once, all flagging reboot-required.

**Disk**:  fsync latency measured ~0.9 ms at rest (SSD-backed), so the datastore disk isn't slow under light load — though I understand latency under load is the relevant factor here.
Confirming this is still a real issue on 1.34 for heavier, continuous workloads, not just the older releases.

**Question**:  is there a target release where this is expected to be fully resolved, or for continuous workloads at this scale is moving to etcd the recommended path? Trying to decide whether to wait on a fix or migrate the datastore.

**Comment by sibelius** [comment]
Try talos

**Comment by QuintusJoyal** [comment]
Any updates? going through similar issue in single node microk8s 1.34

**Comment by jackgarveylinkforce** [comment]
Any news on when there will be a fix for this?

**Comment by williamjoye** [comment]
Hi,

I believe I am seeing the same issue on a more recent MicroK8s version, and I was able to capture the `k8s-dqlite` retry behaviour described in this issue.

## Environment

- MicroK8s: **v1.36.2**, snap revision **9092**
- Channel: `1.36/stable`
- k8s-dqlite: **v1.8.1**
- k8s-dqlite commit: `c22704200d18466b1e638cbd489eba92458306cb`
- dqlite: **1.18.2**
- SQLite: **3.50.2**
- libuv: **1.48.0**
- 3-node HA cluster

The issue is reproducible on the two currently active datastore nodes and affects unrelated Kubernetes resources, especially Lease updates, but also Longhorn resources and other writes.

Typical errors are:

```text
exec (try: 500): database is locked
```

and, during more severe periods:

```text
context deadline exceeded
```

## Retry behaviour

I enabled debug logging long enough to capture one of these failures.

Immediately before the final error, `k8s-dqlite` logged:

```text
update_sql (try: 493)
update_sql (try: 494)
update_sql (try: 495)
update_sql (try: 496)
update_sql (try: 497)
update_sql (try: 498)
update_sql (try: 499)
exec (try: 500): database is locked
```

This matches the implementation in `pkg/backend/sqlite/driver.go` in the exact k8s-dqlite revision shipped by MicroK8s 1.36.2.

`execute()` retries `SQLITE_BUSY` up to `maxRetries = 500`:

```go
for ; retryCount < maxRetries; retryCount++ {
    result, err = d.config.DB.ExecContext(ctx, query, args...)
    if err == nil {
        break
    }
    if !d.config.Retry(err) {
        break
    }
}
```

The default retry predicate considers `sqlite3.ErrBusy` retryable.

An important observation is that there is **no sleep/backoff/jitter between retries in this `execute()` path**. Therefore a single Kubernetes update that encounters `SQLITE_BUSY` can result in hundreds of immediate internal `ExecContext()` attempts before finally returning `database is locked`.

I also checked the current `master` implementation and this retry loop still appears to work the same way.

## API request rate

I initially suspected an unusually high Kubernetes Lease update rate, but a clean 5-minute measurement does not support that hypothesis:

```text
Lease PUT:
HTTP 200 : 1117   223.40/min   3.72/sec
HTTP 500 :    3     0.60/min   0.01/sec
HTTP 504 :    0
TOTAL    : 1120   224.00/min   3.73/sec
```

During the same 5-minute interval, k8s-dqlite logged 13 `database is locked` failures.

Therefore, in this reproduction, the high number of internal retries is not explained by an exceptionally high Lease API request rate.

## Additional observations

The locking is not limited to a single Kubernetes object or controller. We have observed it on:

- Kubernetes Leases
- Longhorn resources
- events
- operator leader-election resources
- other unrelated registry writes

The issue is also visible independently on both active datastore nodes. The lock timestamps are generally **not synchronized between the two nodes**, which suggests local transaction contention in each k8s-dqlite frontend rather than a single cluster-wide event occurring simultaneously on all nodes.

We also observed periods of significant disk I/O latency during the original incident. However, subsequent measurements show that persistent physical NVMe saturation is not required for the issue to occur.

My current assumption is therefore that I/O latency may amplify the problem by increasing the time a writer holds the database lock, rather than being the primary cause.

## Impact

During the most severe occurrence, the sequence was approximately:

```text
kine/dqlite errors
    ↓
repeated "database is locked"
    ↓
Kubernetes write failures / context deadlines
    ↓
control-plane degradation
    ↓
API timeouts
```

A later memory-pressure/OOM event significantly amplified the incident, but importantly, the kine/dqlite errors and `database is locked` messages were already present before the OOM.

## Possible relation to this issue

This looks very similar to the behaviour reported here: a relatively small number of Kubernetes updates can result in a much larger number of internal SQL execution attempts when SQLite returns `BUSY`.

The reproduction on **MicroK8s 1.36.2 / k8s-dqlite 1.8.1** also indicates that the behaviour is still present in a significantly newer version than the 1.32/1.33 versions originally discussed in this issue.

I am not claiming that the retry loop itself is necessarily the initial cause of `SQLITE_BUSY`, but it appears capable of significantly **amplifying contention once a BUSY condition occurs**.

I can provide additional debug logs, exact timestamps, datastore metrics, or perform targeted non-destructive tests if that would help investigate the root cause.
