### ISSUE TITLE
Microk8s on armhf architecture

### ISSUE THREAD

**Issue by CalvinHartwell** [canonical/microk8s#719]
Hi all, 

The armhf binary is missing and not available right now, which means that some users cannot install microk8s on Ubuntu. For example, if you use the armhf image for Raspberry Pi, you cannot install microk8s: 

> ubuntu@battlecruiser:~$ sudo snap install microk8s --classic
> error: snap "microk8s" is not available on stable for this architecture (armhf)
>        but exists on other architectures (amd64, arm64, ppc64el).

It would be really good if we could also get the build compiled for this architecture and make officially available. 

Cheers,

- Calvin

**Comment by recklessop** [comment]
this is a duplicate issue of https://github.com/ubuntu/microk8s/issues/228

**Comment by CalvinHartwell** [comment]
@recklessop you're correct yes, my apologies. I have hardware available we could use to address the problem.

**Comment by iam-TJ** [comment]
Does the detail at:

https://microk8s.io/docs/install-alternatives#arm

"... This can be remedied on the Rasberry Pi by editing the boot parameters: ..."

imply that  this is now solved?

**Comment by ktsakalozos** [comment]
> imply that this is now solved?

No the issue is not resolved. The instructions are for arm64 not for armhf. We currently do not build for this architecture. You can try to create a build yourself by git cloneing the repo and running  `snapcraft` possibly in a remote build as described here https://forum.snapcraft.io/t/preview-snapcraft-remote-build/11541 Note that we have not tested this so any patches you can provide are welcomed.

**Comment by bragdonjm** [comment]
Running into this now myself.

**Comment by stevieray8450** [comment]
running into this is as well.

I've tried using `snapcraft remote-build` as well. I get this error:

> Remote-build does not support the use of `version-script`.
> Please use `snapcraftctl set-version` part scriptlet with `adopt-info`, or set `version` statically.

**Comment by erasmus74** [comment]
Also running into this, dietpi on RPI4 all recent builds as of this date

**Comment by ktsakalozos** [comment]
@erasmus74 I am fairly certain RPi4 is on ARM64. Could you double check the OS you have installed?

**Comment by erasmus74** [comment]
You're correct, I was on armhf/32-bit, switching to 64bit worked like a charm

**Comment by forzagreen** [comment]
Same issue on Raspberry PI 3 B.
I ended up using [k3s](https://k3s.io/).

**Comment by angelnu** [comment]
I also run in the same issue with some Odroids XU4 where I had previously used upstream k8s. I just did a PoC build directly in the device and it did work after I commented out the etcd snap part ot built. The issue with etcd is that they do not build for arm so it would need to be built from sources - doable but since etcd is not really needed not key for a PoC.

Now trying to run I see two issues:
- scripts/wrappers/common/utils.py is missing a mapping for the `armv7l` arch so kubectl status fails. I will add and rebuild
- the k8s api service is not running - not debugged yet.

Output from microk8s inspect:
```
root@n5:~/microk8s# microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
```
Will continue tomorrow.

@ktsakalozos - in case it makes sense to add to your pipeline and submit a PR - do you build on remote or do you have native arm HW?

**Comment by angelnu** [comment]
Added support for remote build and tested the build local and remote with v1.20.0 (btw: latest is currently broken -> patch does not apply).

Calico (needed for HA) is not available on armhf yet:
- https://github.com/projectcalico/cni-plugin/issues/869
- https://github.com/projectcalico/calico/issues/3583

**Comment by ntindle** [comment]
> Added support for remote build and tested the build local and remote with v1.20.0 (btw: latest is currently broken -> patch does not apply).
> 
> Calico (needed for HA) is not available on armhf yet:
> 
> * [Support for linux/arm/v7 projectcalico/cni-plugin#869](https://github.com/projectcalico/cni-plugin/issues/869)
> * [Support for armhf projectcalico/calico#3583](https://github.com/projectcalico/calico/issues/3583)

I belive the two of these are now supported

**Comment by davidmco65** [comment]
Please help me out here... I see this issue has fixes committed but the issue is still open, so have they not been merged yet?  The fixes were applied in February 2021 and it's now December, am I missing something?  I'm getting this error on both RPi 3B+ and 4.  Thanks!
